name: Build, Test and Deploy

on: [push]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.FIREBASE_MESSAGE_SENDER_ID }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_DOMAIN: ${{ secrets.SENDGRID_DOMAIN }}
  MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
  MAILCHIMP_API_URI: ${{ secrets.MAILCHIMP_API_URI }}
  MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
  WEBSITE_URI: ${{ secrets.WEBSITE_URI }}

jobs:
  test-api:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install firebase
        run: |
          npm install -g firebase-tools
      - name: Install API dependencies
        run: |
          cd functions
          npm install
      - name: Build API
        run: |
          cd functions
          npm run build
    #   - name: Test Functions (currently issues running email parser on GitHub actions)
    #     run: |
    #       cd functions
    #       firebase functions:config:get --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN} > .runtimeconfig.json
    #       npm run test

  test-ui:
    name: Test UI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd hosting
          npm install
      - name: Lint check
        run: |
          cd hosting
          npm run lint
      - name: Build site
        run: |
          cd hosting
          npm run build

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test-api, test-ui]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Tools
        run: |
          npm install
      - name: Build UI
        run: |
          cd hosting
          npm install
          sed -i 's|{{ FIREBASE_API_KEY }}|'${FIREBASE_API_KEY}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_APP_ID }}|'${FIREBASE_APP_ID}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_AUTH_DOMAIN }}|'${FIREBASE_AUTH_DOMAIN}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_MESSAGE_SENDER_ID }}|'${FIREBASE_MESSAGE_SENDER_ID}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_PROJECT_ID }}|'${FIREBASE_PROJECT_ID}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_STORAGE_BUCKET }}|'${FIREBASE_STORAGE_BUCKET}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ FIREBASE_MEASUREMENT_ID }}|'${FIREBASE_MEASUREMENT_ID}'|g' src/environments/environment.prod.ts
          sed -i 's|{{ SENDGRID_DOMAIN }}|'${SENDGRID_DOMAIN}'|g' src/environments/environment.prod.ts
          npm run build
      - name: Build Functions
        run: |
          cd functions
          npm install
      - name: Deploy
        run: |
          npx firebase functions:config:set sendgrid.api_key=${SENDGRID_API_KEY} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase functions:config:set sendgrid.domain=${SENDGRID_DOMAIN} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase functions:config:set mailchimp.api_key=${MAILCHIMP_API_KEY} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase functions:config:set mailchimp.api_uri=${MAILCHIMP_API_URI} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase functions:config:set mailchimp.list_id=${MAILCHIMP_LIST_ID} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase functions:config:set website.uri=${WEBSITE_URI} --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          npx firebase deploy --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN} --force
